"""your message

Revision ID: b706bc93d7cd
Revises: c4d627a3d3dc
Create Date: 2024-10-20 22:49:18.942779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b706bc93d7cd'
down_revision = 'c4d627a3d3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
